<LettersWidget>:

    Label:
        id: letter
        text: root.letter
        # text_size: root.width, root.height
        halign: 'center'
        valign: 'middle'
        font_size: 360
        center_x: root.center_x
        center_y: root.center_y

    Label:
        id: score
        text: root.score
        # text_size: root.width, root.height / 4
        # top: root.bottom - self.height
