<LettersWidget>:

    Label:
        id: letter
        text: root.letter
        halign: 'center'
        valign: 'middle'
        font_size: root.height
        center_x: root.center_x
        center_y: root.center_y

    Label:
        id: score
        text: root.score
        font_size: root.height / 4
        center_y: root.center_y
        center_x: root.center_x
        color: root.score_color
